name: digital_bank_app
description: A minimal Flutter app scaffolded with Clean Architecture for the digital bank project.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  dio: ^5.2.1
  get_it: ^8.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
